# **NUMPY**

numpy is a general purpose array processing package .It provides high performance multi-dimenssional array objects and tools for working with these arrays


In [1]:
import numpy as np

**Array**

it is a data structure that holds one type of value only unlike lists


In [4]:
# how to make numpy array
#start with the list
my_list=list()
my_list.append(1)
my_list.append(2)
my_list.append(3)
my_list.append(4)
my_list.append(5)
my_list

[1, 2, 3, 4, 5]

In [6]:
#convert into numpy array
arr=np.array(my_list)  # always make sure to use element of same type when converting to arr
print(arr)

[1 2 3 4 5]


In [7]:
type(arr)

numpy.ndarray

In [9]:
# shape function gives (n,m) dimension of array
arr.shape

(5,)

In [12]:
#how to make multi dimenssion array
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
list3=[11,12,13,14,15]
arr=np.array([list1,list2,list3])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [13]:
arr.shape


(3, 5)

In [14]:
#now reshaping remeber when reshapin in a*b dimmesion it remain same with n*m
arr.reshape(5,3)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [15]:
#but remeber this reshaping does not modify the array
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [16]:
#indexing
arr=np.array([1,2,3,4,5])
arr[2]

3

In [18]:
#indexing for 2-D array
# arr[a:b,c:d] - a:b signifies that row from where to where and b always +1
#                c:d signifies column form where to where and d always +1

array=np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]])
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
#now i want you to print [6,7],
#                         [10,11]

array[1:3,1:3]



array([[ 6,  7],
       [10, 11]])

In [24]:
# to get the element in the particular range THIRD PARA IS STEP SIZE
demo=np.arange(0,10)
demo

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
demo=np.arange(0,10,2)
demo

array([0, 2, 4, 6, 8])

In [25]:
#making copy and broadcasting
arr[3:]=100
arr

array([  1,   2,   3, 100, 100])

In [27]:
arr2=arr
arr2[3:]=500
arr2

array([  1,   2,   3, 500, 500])

In [28]:
arr

array([  1,   2,   3, 500, 500])

In [ ]:
#see both array has changed tho i made the changes in arr2 since they are refrence data type
#they share same memory so if u have to make changes and make sure original does
#not get modified use COPY


In [30]:
arr3=arr.copy()
arr3[3:]=1000
arr3

array([   1,    2,    3, 1000, 1000])

In [31]:
arr

array([  1,   2,   3, 500, 500])

In [32]:
# some condition useful EDA
val=2
arr<2

array([ True, False, False, False, False])

In [33]:
arr[arr<2]

array([1])

In [34]:
arr*2

array([   2,    4,    6, 1000, 1000])

In [35]:
arr+4

array([  5,   6,   7, 504, 504])

In [36]:
#ones function
np.ones((2,5),dtype=int)


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [37]:
# random distribution
np.random.rand(3,3)

array([[0.07499069, 0.51844355, 0.01544995],
       [0.28415189, 0.11926642, 0.49601993],
       [0.5890907 , 0.81836209, 0.24695793]])

In [39]:
#random standard normal distribution
np.random.rand(3,3)

array([[0.63657849, 0.51546592, 0.72608407],
       [0.518691  , 0.81530251, 0.07515652],
       [0.66115649, 0.52879848, 0.64174091]])